version: '3'

services:

   node:
     build:
        context: node
        dockerfile: Dockerfile
     environment:
       - CHOKIDAR_USEPOLLING
     ports:
       - "${NODE_PORT:-8080}:8080"
     volumes:
       - ".:/app"
